Repository DreamUnibucTeam/FriendSync, pull requests merged in 2021-05, with the labels that each got.

#9 feat: Adding Firebase
  .gitignore
  app.js
  client/.gitignore
  client/src/context/FirebaseContext.jsx
  client/src/firebase/firebase.js
  client/src/firebase/firebaseConfig.js
  config/serviceAccount.js
  firebase/firebase.admin.js
  package-lock.json
  package.json
Labels: backend, firebase, frontend

#29 feat: Refactoring and testing the Rest API with Thunder Client
  controllers/group.controller.js
  controllers/user.controller.js
Labels: backend

#31 feat: Adding unit tests for the API functions
  __tests__/requests/groups.test.js
  __tests__/requests/users.test.js
  controllers/user.controller.js
  package-lock.json
  package.json
Labels: backend, testing

#32 Chat Screen
  client/android/app/src/main/AndroidManifest.xml
  client/android/build.gradle
  client/ios/Podfile
  client/ios/client/AppDelegate.m
  client/ios/client/Info.plist
  client/package-lock.json
  client/package.json
  client/src/screens/chat/chat.component.jsx
  client/src/screens/chat/chat.data.js
  client/src/screens/chat/chat.styles.jsx
  client/src/screens/contacts/contacts.component.jsx
  client/src/screens/groups/groups.component.jsx
  client/src/screens/map/map.component.jsx
  client/src/stacks/ChatStack.jsx
  client/src/stacks/GroupStackScreens.jsx
  client/src/stacks/MainStackScreens.jsx
Labels: frontend

#30 feat: Adding Homescreen and UI Kitten library
  client/App.js
  client/package-lock.json
  client/package.json
  client/src/components/homescreen-container/homescreen-container.component.jsx
  client/src/components/homescreen-container/homescreen-container.styles.js
  client/src/screens/authScreens/signup/signUpScreen.component.jsx
  client/src/screens/home/home.component.jsx
  client/src/screens/home/home.styles.js
Labels: frontend

#33 feat: Groups Screen UI and Functionality
  README.md
  client/App.js
  client/package-lock.json
  client/package.json
  client/src/components/FocusAwareStatusBar/FocusAwareStatusBar.component.jsx
  client/src/components/group/group.component.jsx
  client/src/context/FirebaseContext.jsx
  client/src/screens/add-group/add-group.component.jsx
  client/src/screens/add-group/add-group.styles.js
  client/src/screens/authScreens/signup/signUpScreen.component.jsx
  client/src/screens/chat/chat.component.jsx
  client/src/screens/groups/groups.component.jsx
  client/src/screens/groups/groups.styles.js
  client/src/screens/home/home.component.jsx
  client/src/stacks/ChatStack.jsx
  client/src/stacks/GroupStackScreens.jsx
  client/src/stacks/MainStackScreens.jsx
  server/.gitignore
  server/controllers/group.controller.js
  server/controllers/user.controller.js
Labels: backend, frontend

#34 feat: Friends
  client/package-lock.json
  client/package.json
  client/src/screens/add-friend/add-friend.component.jsx
  client/src/screens/add-friend/add-friend.styles.js
  client/src/screens/contacts/contacts.component.jsx
  client/src/screens/contacts/contacts.styles.js
  client/src/screens/friends/friends.component.jsx
  client/src/screens/friends/friends.styles.js
  client/src/screens/groups/groups.component.jsx
  client/src/screens/groups/groups.styles.js
  client/src/screens/home/home.component.jsx
  client/src/screens/home/home.styles.js
  client/src/stacks/FriendsStackScreens.jsx
  client/src/stacks/MainStackScreens.jsx
  server/controllers/user.controller.js
  server/routes/users.routes.js
Labels: backend, frontend

#36 Added API endpoints for meetings and activities
  server/controllers/meeting.controller.js
  server/package-lock.json
  server/package.json
  server/routes/meetings.routes.js
Labels: backend, database

#37 feat: Added ability to delete a group and add users and Bug fixes
  client/App.js
  client/package-lock.json
  client/package.json
  client/src/components/loading-page/loading-page.component.jsx
  client/src/components/loading-page/loading-page.styles.js
  client/src/context/GroupContext.jsx
  client/src/screens/add-friend/add-friend.component.jsx
  client/src/screens/add-group-member/add-group-member.component.jsx
  client/src/screens/add-group-member/add-group-member.styles.js
  client/src/screens/chat/chat.component.jsx
  client/src/screens/friends/friends.component.jsx
  client/src/screens/group-settings/group-settings.component.jsx
  client/src/screens/group-settings/group-settings.styles.js
  client/src/screens/groups/groups.component.jsx
  client/src/screens/home/home.component.jsx
  client/src/stacks/ChatStack.jsx
  client/src/stacks/GroupMembersStackScreens.jsx
  server/controllers/group.controller.js
  server/controllers/meeting.controller.js
  server/controllers/user.controller.js
  server/routes/groups.routes.js
Labels: frontend

#38 feat: Implement "Add Meeting" screen
  client/package-lock.json
  client/package.json
  client/src/components/customListItem/customListItem.component.jsx
  client/src/components/customListItem/customListItem.styles.js
  client/src/context/GroupContext.jsx
  client/src/hooks/http.hook.jsx
  client/src/screens/add-friend/add-friend.component.jsx
  client/src/screens/add-meeting/add-meeting.component.jsx
  client/src/screens/add-meeting/add-meeting.styles.js
  client/src/screens/groups/groups.component.jsx
  client/src/screens/map/map.component.jsx
  client/src/screens/meetings/meetings.component.jsx
  client/src/screens/meetings/meetings.styles.js
  client/src/screens/schedule/schedule.component.jsx
  client/src/screens/schedule/schedule.styles.js
  client/src/stacks/ChatStack.jsx
  client/src/stacks/GroupMeetingsStackScreens.jsx
  client/src/stacks/GroupStackScreens.jsx
  client/src/stacks/MeetingStackScreens.jsx
  server/app.js
Labels: frontend

#47 Adding Bug Reporting page and it's fuctionality
  client/src/screens/report/report.component.jsx
  client/src/screens/report/report.data.js
  client/src/screens/report/report.styles.js
  client/src/stacks/MainStackScreens.jsx
  client/src/stacks/ProfileStackScreens.jsx
Labels: frontend
